"""Special-offers product seed (toys-accessories / innovation-tech / services).

Loaded by seed_products.seed_products_if_empty().
"""

# Image pool reused for variety.
IMG = {
    "rope": "https://images.pexels.com/photos/1390784/pexels-photo-1390784.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "kong": "https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "ball": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "scratch": "https://images.pexels.com/photos/1543793/pexels-photo-1543793.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "harness": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "bed": "https://images.pexels.com/photos/3361739/pexels-photo-3361739.jpeg?auto=compress&cs=tinysrgb&w=1200",

    "feeder": "https://images.pexels.com/photos/27435433/pexels-photo-27435433.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "fountain": "https://images.pexels.com/photos/8434670/pexels-photo-8434670.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "gps": "https://images.pexels.com/photos/4587971/pexels-photo-4587971.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "cam": "https://images.pexels.com/photos/5731866/pexels-photo-5731866.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "litter_robot": "https://images.pexels.com/photos/6957007/pexels-photo-6957007.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "tracker": "https://images.pexels.com/photos/7210262/pexels-photo-7210262.jpeg?auto=compress&cs=tinysrgb&w=1200",

    "groom": "https://images.pexels.com/photos/6816858/pexels-photo-6816858.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "vet": "https://images.pexels.com/photos/6235233/pexels-photo-6235233.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "walk": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "train": "https://images.pexels.com/photos/4587959/pexels-photo-4587959.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "sit": "https://images.pexels.com/photos/3361739/pexels-photo-3361739.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "microchip": "https://images.pexels.com/photos/6235233/pexels-photo-6235233.jpeg?auto=compress&cs=tinysrgb&w=1200",
}


SPECIALS_PRODUCTS = [
    # -------- TOYS & ACCESSORIES --------
    {
        "slug": "kong-classic-rubber-toy",
        "name": "Kong Classic Rubber Toy",
        "brand": "Kong",
        "sub_category": "toys-accessories",
        "pet_type": "dog",
        "image": IMG["kong"],
        "description": "The original red ultra-tough rubber toy. Stuff with treats for hours of enrichment — dishwasher safe.",
        "size": "S · M · L · XL",
        "tags": ["chew", "enrichment", "durable"],
        "featured": True,
    },
    {
        "slug": "trixie-cotton-rope-tug",
        "name": "Trixie Cotton Rope Tug",
        "brand": "Trixie",
        "sub_category": "toys-accessories",
        "pet_type": "dog",
        "image": IMG["rope"],
        "description": "Knotted cotton rope tug for shared play. Cleans teeth while you wrestle for it.",
        "size": "35 cm · 50 cm",
        "tags": ["fetch", "dental", "interactive"],
    },
    {
        "slug": "petsafe-busy-buddy-ball",
        "name": "PetSafe Busy Buddy Treat Ball",
        "brand": "PetSafe",
        "sub_category": "toys-accessories",
        "pet_type": "both",
        "image": IMG["ball"],
        "description": "Adjustable treat-dispensing ball that slows feeding and keeps clever pets entertained.",
        "size": "S · M · L",
        "tags": ["enrichment", "slow-feed"],
    },
    {
        "slug": "ferplast-sisal-scratch-post",
        "name": "Ferplast Tindra Scratch Post",
        "brand": "Ferplast",
        "sub_category": "toys-accessories",
        "pet_type": "cat",
        "image": IMG["scratch"],
        "description": "Tall sisal scratch post with a perched lookout platform. Saves your sofa, your sanity and your cat's claws.",
        "size": "65 cm",
        "tags": ["scratching", "vertical"],
        "featured": True,
    },
    {
        "slug": "hunter-padded-harness",
        "name": "Hunter Hilo Padded Harness",
        "brand": "Hunter",
        "sub_category": "toys-accessories",
        "pet_type": "dog",
        "image": IMG["harness"],
        "description": "Step-in padded harness with reflective trim. Even weight distribution for daily walks.",
        "size": "XS · S · M · L · XL",
        "tags": ["walk", "reflective"],
    },
    {
        "slug": "outward-hound-orthopedic-bed",
        "name": "Outward Hound ThermoPro Orthopedic Bed",
        "brand": "Outward Hound",
        "sub_category": "toys-accessories",
        "pet_type": "both",
        "image": IMG["bed"],
        "description": "Memory-foam bed with bolster sides. Joint support for seniors and a cosy nest for snoozers.",
        "size": "M · L · XL",
        "tags": ["bed", "orthopedic", "senior"],
    },

    # -------- INNOVATION & TECH --------
    {
        "slug": "smartpaw-smart-feeder-pro",
        "name": "SmartPaw Smart Feeder Pro",
        "brand": "SmartPaw",
        "sub_category": "innovation-tech",
        "pet_type": "both",
        "image": IMG["feeder"],
        "description": "Wi-Fi feeder that portions meals to your plan, logs intake and alerts you if a meal is missed. Free with eligible annual subscriptions.",
        "size": "6L hopper",
        "tags": ["feeder", "wifi", "subscription-bundle"],
        "featured": True,
    },
    {
        "slug": "petkit-eversweet-fountain",
        "name": "Petkit Eversweet 3 Fountain",
        "brand": "Petkit",
        "sub_category": "innovation-tech",
        "pet_type": "both",
        "image": IMG["fountain"],
        "description": "Triple-filtered water fountain with a near-silent pump. Encourages drinking — vital for kidney health in cats.",
        "size": "2 L",
        "tags": ["water", "filtration", "silent"],
    },
    {
        "slug": "tractive-gps-tracker",
        "name": "Tractive GPS Tracker",
        "brand": "Tractive",
        "sub_category": "innovation-tech",
        "pet_type": "both",
        "image": IMG["gps"],
        "description": "Live GPS tracking with virtual fence alerts and activity monitoring. Lightweight collar clip — escape-proof.",
        "size": "One size · subscription",
        "tags": ["gps", "safety", "tracker"],
        "featured": True,
    },
    {
        "slug": "furbo-360-treat-cam",
        "name": "Furbo 360° Dog Camera",
        "brand": "Furbo",
        "sub_category": "innovation-tech",
        "pet_type": "dog",
        "image": IMG["cam"],
        "description": "360° rotating camera with two-way audio and treat tossing. Barking alerts when you're out.",
        "size": "One size",
        "tags": ["camera", "two-way-audio", "alerts"],
    },
    {
        "slug": "petsafe-scoopfree-litter",
        "name": "PetSafe ScoopFree Self-Cleaning Litter Box",
        "brand": "PetSafe",
        "sub_category": "innovation-tech",
        "pet_type": "cat",
        "image": IMG["litter_robot"],
        "description": "Hands-free self-cleaning litter box with crystal litter. Cleans for weeks between refills.",
        "size": "Standard · Ultra",
        "tags": ["self-cleaning", "hygiene"],
    },
    {
        "slug": "sure-petcare-microchip-feeder",
        "name": "Sure Petcare SureFeed Microchip Feeder",
        "brand": "Sure Petcare",
        "sub_category": "innovation-tech",
        "pet_type": "cat",
        "image": IMG["tracker"],
        "description": "Microchip-activated bowl opens only for your pet — perfect for multi-pet households and prescription diets.",
        "size": "One bowl",
        "tags": ["feeder", "microchip", "multi-pet"],
    },

    # -------- SERVICES --------
    {
        "slug": "mobile-grooming-session",
        "name": "Mobile Grooming Session",
        "brand": "SmartPaw Partners",
        "sub_category": "services",
        "pet_type": "both",
        "image": IMG["groom"],
        "description": "Bath, blow-dry, brush, nail clipping and ear cleaning — done at your door by certified groomers.",
        "size": "60–90 min",
        "tags": ["grooming", "at-home"],
        "featured": True,
    },
    {
        "slug": "vet-home-checkup",
        "name": "Vet Home Check-up",
        "brand": "Partner Vets",
        "sub_category": "services",
        "pet_type": "both",
        "image": IMG["vet"],
        "description": "Licensed vet visit at your home for vaccinations, wellness checks and minor procedures. Anxiety-friendly.",
        "size": "30–45 min",
        "tags": ["vet", "at-home", "vaccination"],
    },
    {
        "slug": "dog-walking-package",
        "name": "Dog Walking Package",
        "brand": "Trusted Walkers",
        "sub_category": "services",
        "pet_type": "dog",
        "image": IMG["walk"],
        "description": "Insured, background-checked walkers — 30 or 60 minute strolls with a photo update at every visit.",
        "size": "5 walks · 10 walks · 20 walks",
        "tags": ["walks", "exercise"],
    },
    {
        "slug": "puppy-training-program",
        "name": "Puppy Training Program",
        "brand": "Certified Trainers",
        "sub_category": "services",
        "pet_type": "dog",
        "image": IMG["train"],
        "description": "6-session positive-reinforcement program covering recall, leash, crate and basic manners.",
        "size": "6 sessions",
        "tags": ["training", "puppy"],
        "featured": True,
    },
    {
        "slug": "pet-sitting-weekend",
        "name": "Weekend Pet Sitting",
        "brand": "SmartPaw Partners",
        "sub_category": "services",
        "pet_type": "both",
        "image": IMG["sit"],
        "description": "In-home sitting while you’re away. Twice-daily visits, feeding, play and litter/poop care.",
        "size": "2 days · 3 days",
        "tags": ["sitting", "travel"],
    },
    {
        "slug": "microchip-id-service",
        "name": "Microchip & ID-Tag Service",
        "brand": "Partner Vets",
        "sub_category": "services",
        "pet_type": "both",
        "image": IMG["microchip"],
        "description": "ISO-standard microchip implantation, registry enrolment and a custom ID-tag delivered to you.",
        "size": "One-time",
        "tags": ["safety", "identification"],
    },
]
