"""SmartPaw catalogue seeder — bilingual, GEL-priced.

Run manually:  python -m backend.seed_smartpet_catalogue

This REPLACES any products with the slugs below (idempotent — re-running
updates fields in place rather than duplicating). Other products are left
intact. Run with --reset to wipe the products collection first.

Data principles:
- Brand + product name + size are factual market data (not copyrightable).
- All descriptions (EN + KA) are freshly written in SmartPaw's voice.
- Images are stock photos from Pexels (free for commercial use, no attribution
  required) chosen to represent the product type. Admins can swap any image
  from the /admin panel later.
- Prices are realistic ranges for the Georgian pet retail market in GEL.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import uuid
from datetime import datetime, timezone
from typing import Dict, List

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient


# ----------------- Stock image pool (Pexels, free for commercial use) -----------------
IMG = {
    # Food
    "kibble_dog": "https://images.pexels.com/photos/8434637/pexels-photo-8434637.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "kibble_cat": "https://images.pexels.com/photos/7210754/pexels-photo-7210754.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "wet_can": "https://images.pexels.com/photos/7210262/pexels-photo-7210262.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "wet_pouch": "https://images.pexels.com/photos/6816859/pexels-photo-6816859.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "treat_strip": "https://images.pexels.com/photos/5731866/pexels-photo-5731866.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "raw_meat": "https://images.pexels.com/photos/4587971/pexels-photo-4587971.jpeg?auto=compress&cs=tinysrgb&w=1200",
    # Hygiene
    "shampoo": "https://images.pexels.com/photos/6568501/pexels-photo-6568501.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "spray": "https://images.pexels.com/photos/6816865/pexels-photo-6816865.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "ear_drops": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "litter": "https://images.pexels.com/photos/6957007/pexels-photo-6957007.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "wipes": "https://images.pexels.com/photos/5731841/pexels-photo-5731841.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "brush": "https://images.pexels.com/photos/6816863/pexels-photo-6816863.jpeg?auto=compress&cs=tinysrgb&w=1200",
    # Vitamins
    "supplement_jar": "https://images.pexels.com/photos/8434641/pexels-photo-8434641.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "joint_tabs": "https://images.pexels.com/photos/5731869/pexels-photo-5731869.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "omega_oil": "https://images.pexels.com/photos/8434670/pexels-photo-8434670.jpeg?auto=compress&cs=tinysrgb&w=1200",
    # Toys & Accessories
    "leash": "https://images.pexels.com/photos/4498185/pexels-photo-4498185.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "collar": "https://images.pexels.com/photos/1390784/pexels-photo-1390784.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "chew_toy": "https://images.pexels.com/photos/5731878/pexels-photo-5731878.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "ball_toy": "https://images.pexels.com/photos/1390361/pexels-photo-1390361.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "bed": "https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "carrier": "https://images.pexels.com/photos/4498132/pexels-photo-4498132.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "bowl": "https://images.pexels.com/photos/4587987/pexels-photo-4587987.jpeg?auto=compress&cs=tinysrgb&w=1200",
    # Innovation & Tech
    "smart_feeder": "https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "gps_tracker": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "pet_camera": "https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "smart_litter": "https://images.pexels.com/photos/6957007/pexels-photo-6957007.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "water_fountain": "https://images.pexels.com/photos/4587987/pexels-photo-4587987.jpeg?auto=compress&cs=tinysrgb&w=1200",
    # Services
    "service_grooming": "https://images.pexels.com/photos/6816863/pexels-photo-6816863.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "service_walking": "https://images.pexels.com/photos/1390784/pexels-photo-1390784.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "service_training": "https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "service_vet": "https://images.pexels.com/photos/6235241/pexels-photo-6235241.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "service_boarding": "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
}


# ====================================================================================
# CATALOGUE -> FOOD (15)
# ====================================================================================
FOOD = [
    {
        "slug": "mera-essential-soft-brocken-adult",
        "name": "Mera Essential Soft Brocken — Adult Dog",
        "name_ka": "Mera Essential Soft Brocken — ზრდასრული ძაღლისთვის",
        "brand": "Mera",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Semi-moist German-made kibble for adult gourmet dogs. Soft texture for easy chewing, with balanced protein from poultry and rice.",
        "description_ka": "გერმანული წარმოების ნახევრად ნოტიო კიბლი ზრდასრული, საქმის მოყვარული ძაღლებისთვის. რბილი ტექსტურა მსუბუქი ღეჭვისთვის, დაბალანსებული პროტეინი ფრინველის ხორცითა და ბრინჯით.",
        "size": "1 kg · 4 kg · 12 kg",
        "price": 204.00,
        "tags": ["dry", "adult", "soft-kibble"],
        "featured": True,
    },
    {
        "slug": "happy-dog-sensible-ireland",
        "name": "Happy Dog Sensible Ireland — Rabbit & Salmon",
        "name_ka": "Happy Dog Sensible Ireland — კურდღელი და ორაგული",
        "brand": "Happy Dog",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Sensitive-stomach dry food made in Germany with novel proteins (rabbit + Atlantic salmon). Grain-light recipe for dogs with food intolerances.",
        "description_ka": "მგრძნობიარე კუჭის მქონე ძაღლებისთვის გერმანული მშრალი საკვები ალტერნატიული ცილოვანი წყაროებით (კურდღელი + ატლანტიკური ორაგული). მარცვლეულის შემცირებული რეცეპტი.",
        "size": "1 kg · 4 kg · 11 kg",
        "price": 19.50,
        "tags": ["dry", "adult", "sensitive", "grain-light"],
    },
    {
        "slug": "natures-protection-maxi-adult-poultry",
        "name": "Nature's Protection Maxi Adult — Poultry",
        "name_ka": "Nature's Protection Maxi Adult — ფრინველის ხორცი",
        "brand": "Nature's Protection",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Lithuanian super-premium kibble for large and giant adult breeds. Joint-friendly nutrient profile with glucosamine and chondroitin.",
        "description_ka": "ლიეტუვური სუპერ-პრემიუმ კიბლი დიდი და გიგანტური ჯიშის ზრდასრული ძაღლებისთვის. სახსრებისთვის სასარგებლო ფორმულა გლუკოზამინითა და ქონდროიტინით.",
        "size": "4 kg · 12 kg",
        "price": 140.70,
        "tags": ["dry", "large-breed", "joint-support"],
        "featured": True,
    },
    {
        "slug": "natures-protection-mini-adult-white-fish",
        "name": "Nature's Protection Mini Adult — White Fish & Krill",
        "name_ka": "Nature's Protection Mini Adult — თეთრი თევზი და კრილი",
        "brand": "Nature's Protection",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Small-breed adult dry food formulated to support a white, healthy coat. White fish protein with Antarctic krill for omega-3 richness.",
        "description_ka": "მცირე ჯიშის ზრდასრული ძაღლების მშრალი საკვები, რომელიც ხელს უწყობს თეთრი, ჯანსაღი ბეწვის შენარჩუნებას. თეთრი თევზის პროტეინი და ანტარქტიკული კრილი ომეგა-3-ის წყაროდ.",
        "size": "1.5 kg · 7.5 kg",
        "price": 32.00,
        "tags": ["dry", "small-breed", "coat-care"],
    },
    {
        "slug": "mera-pure-sensitive-salmon-rice",
        "name": "Mera Pure Sensitive — Salmon & Rice",
        "name_ka": "Mera Pure Sensitive — ორაგული და ბრინჯი",
        "brand": "Mera",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Single-protein hypoallergenic recipe with Atlantic salmon and rice. Ideal as an elimination diet for dogs with allergies.",
        "description_ka": "ერთ-პროტეინიანი ჰიპოალერგენული რეცეპტი ატლანტიკური ორაგულითა და ბრინჯით. იდეალური ალერგიის მქონე ძაღლებისთვის ელიმინაციური დიეტისთვის.",
        "size": "1 kg · 4 kg · 12.5 kg",
        "price": 19.00,
        "tags": ["dry", "hypoallergenic", "single-protein"],
    },
    {
        "slug": "happy-cat-minkas-hairball-control",
        "name": "Happy Cat Minkas Hairball Control",
        "name_ka": "Happy Cat Minkas Hairball Control",
        "brand": "Happy Cat",
        "pet_type": "cat",
        "image": IMG["kibble_cat"],
        "description": "German dry cat food with a specialised fibre matrix that helps move ingested hair through the digestive tract. Reduces hairball formation.",
        "description_ka": "გერმანული მშრალი საკვები კატებისთვის. სპეციალური ბოჭკოვანი ფორმულა, რომელიც ეხმარება გაყლაპული ბეწვის გადატანას საჭმლის მომნელებელი ტრაქტიდან. ამცირებს ბეწვის ბურთულების წარმოქმნას.",
        "size": "1.5 kg · 4 kg · 10 kg",
        "price": 20.25,
        "tags": ["dry", "cat", "hairball-control"],
    },
    {
        "slug": "mera-univit-mix-menu",
        "name": "Mera Univit Mix Menu — Adult Dog",
        "name_ka": "Mera Univit Mix Menu — ზრდასრული ძაღლი",
        "brand": "Mera",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Daily-feed dry mix for adult dogs across all sizes. Includes vitamin and mineral premix to round out home-prepared meals.",
        "description_ka": "ყოველდღიური მშრალი ნარევი ნებისმიერი ზომის ზრდასრული ძაღლისთვის. შეიცავს ვიტამინებისა და მინერალების პრემიქსს სახლის რაციონის შესავსებად.",
        "size": "12.5 kg",
        "price": 166.00,
        "tags": ["dry", "all-sizes", "supplement-mix"],
    },
    {
        "slug": "purepets-cat-tuna-anchovy-gravy",
        "name": "Purepets Cat — Tuna & Anchovy in Gravy",
        "name_ka": "Purepets Cat — ტუნა და ანჩოუსი სოუსში",
        "brand": "Purepets",
        "pet_type": "cat",
        "image": IMG["wet_can"],
        "description": "Tender tuna and anchovy chunks in a savoury gravy. Single-serve pouch — complete and balanced for adult cats.",
        "description_ka": "ნაზი ტუნისა და ანჩოუსის ნაჭრები გემრიელ სოუსში. ერთჯერადი პაკეტი — სრული და დაბალანსებული ზრდასრული კატებისთვის.",
        "size": "400 g",
        "price": 3.80,
        "tags": ["wet", "cat", "gravy"],
    },
    {
        "slug": "purepets-cat-chicken-gravy",
        "name": "Purepets Cat — Chicken in Gravy",
        "name_ka": "Purepets Cat — ქათამი სოუსში",
        "brand": "Purepets",
        "pet_type": "cat",
        "image": IMG["wet_can"],
        "description": "Slow-cooked chicken chunks in a light, aromatic gravy. A reliable everyday wet meal for adult cats.",
        "description_ka": "ნელ-ნელა მოხარშული ქათმის ნაჭრები მსუბუქი, არომატული სოუსით. ყოველდღიური სარწმუნო სველი კერძი ზრდასრული კატებისთვის.",
        "size": "400 g",
        "price": 3.80,
        "tags": ["wet", "cat", "gravy"],
    },
    {
        "slug": "purepets-sterilised-cat-salmon-gravy",
        "name": "Purepets Sterilised Cat — Salmon in Gravy",
        "name_ka": "Purepets Sterilised Cat — ორაგული სოუსში",
        "brand": "Purepets",
        "pet_type": "cat",
        "image": IMG["wet_can"],
        "description": "Designed for neutered or spayed cats. Lean salmon chunks in gravy with controlled fat and added L-carnitine to support healthy body weight.",
        "description_ka": "კასტრირებული ან სტერილიზებული კატებისთვის. მჭლე ორაგულის ნაჭრები სოუსში კონტროლირებული ცხიმის შემცველობით და L-კარნიტინით ჯანსაღი წონის შესანარჩუნებლად.",
        "size": "400 g",
        "price": 4.10,
        "tags": ["wet", "cat", "sterilised", "weight-control"],
    },
    {
        "slug": "purepets-dog-lamb-gravy",
        "name": "Purepets Adult Dog — Lamb Chunks in Gravy",
        "name_ka": "Purepets Adult Dog — ცხვრის ხორცის ნაჭრები სოუსში",
        "brand": "Purepets",
        "pet_type": "dog",
        "image": IMG["wet_pouch"],
        "description": "Tender lamb chunks in savoury gravy. A complete wet meal that can be served alone or mixed with kibble for a topper.",
        "description_ka": "ნაზი ცხვრის ხორცის ნაჭრები გემრიელ სოუსში. სრული სველი კერძი, რომელიც შეიძლება მიეცეს ცალკე ან მშრალ კიბლთან ერთად.",
        "size": "400 g",
        "price": 3.80,
        "tags": ["wet", "dog", "gravy"],
    },
    {
        "slug": "purepets-dog-beef-gravy",
        "name": "Purepets Adult Dog — Beef Chunks in Gravy",
        "name_ka": "Purepets Adult Dog — საქონლის ხორცის ნაჭრები სოუსში",
        "brand": "Purepets",
        "pet_type": "dog",
        "image": IMG["wet_pouch"],
        "description": "Rich beef chunks slow-simmered in gravy. High palatability for picky eaters and excellent moisture content for hydration.",
        "description_ka": "მდიდარი საქონლის ხორცის ნაჭრები ნელ-ნელა მოხარშული სოუსში. მაღალი გემრიელობა გემოვნებიანი ცხოველებისთვის და კარგი ტენიანობა ჰიდრატაციისთვის.",
        "size": "400 g",
        "price": 3.80,
        "tags": ["wet", "dog", "gravy"],
    },
    {
        "slug": "smartpaw-puppy-starter",
        "name": "SmartPaw Puppy Starter — Chicken & Rice",
        "name_ka": "SmartPaw Puppy Starter — ქათამი და ბრინჯი",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Our own starter recipe for puppies 2–12 months. Small kibble size, DHA for brain development and a calcium/phosphorus ratio tuned for growing bones.",
        "description_ka": "ჩვენი საკუთარი რეცეპტი 2–12 თვის ლეკვებისთვის. პატარა კიბლის ზომა, DHA ტვინის განვითარებისთვის და ძვლების ზრდისთვის ოპტიმიზებული კალციუმ-ფოსფორის თანაფარდობა.",
        "size": "1 kg · 3 kg",
        "price": 28.00,
        "tags": ["dry", "puppy", "growth"],
        "featured": True,
    },
    {
        "slug": "smartpaw-kitten-starter",
        "name": "SmartPaw Kitten Starter — Salmon",
        "name_ka": "SmartPaw Kitten Starter — ორაგული",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["kibble_cat"],
        "description": "Calorie-rich growth food for kittens 8 weeks – 12 months. Norwegian salmon as the first ingredient with taurine and DHA support.",
        "description_ka": "კალორიებით მდიდარი საკვები 8 კვირიდან 12 თვემდე კნუტებისთვის. ნორვეგიული ორაგული, როგორც პირველი ინგრედიენტი, ტაურინითა და DHA-თი.",
        "size": "1 kg · 2 kg",
        "price": 32.00,
        "tags": ["dry", "kitten", "growth"],
    },
    {
        "slug": "smartpaw-senior-dog-light",
        "name": "SmartPaw Senior Dog Light — Turkey",
        "name_ka": "SmartPaw Senior Dog Light — ინდაური",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["kibble_dog"],
        "description": "Reduced-calorie kibble for senior dogs 8+ years. Lean turkey, joint-supporting glucosamine and antioxidants for ageing cells.",
        "description_ka": "შემცირებული კალორიის კიბლი 8+ წლის ხანდაზმული ძაღლებისთვის. მჭლე ინდაური, გლუკოზამინი სახსრებისთვის და ანტიოქსიდანტები მოხუცი უჯრედებისთვის.",
        "size": "2.5 kg · 7 kg",
        "price": 42.00,
        "tags": ["dry", "senior", "weight-control"],
    },
]


# ====================================================================================
# CATALOGUE -> HYGIENE (15)
# ====================================================================================
HYGIENE = [
    {
        "slug": "iv-san-bernard-talc-shampoo",
        "name": "Iv San Bernard Talc Shampoo — Puppies & Kittens",
        "name_ka": "Iv San Bernard Talc Shampoo — ლეკვებისა და კნუტებისთვის",
        "brand": "Iv San Bernard",
        "pet_type": "both",
        "image": IMG["shampoo"],
        "description": "Italian gentle shampoo with a signature talc fragrance. PH-balanced for puppies, kittens and sensitive adult skin.",
        "description_ka": "იტალიური ნაზი შამპუნი დამახასიათებელი ტალკის სურნელით. დაბალანსებული pH ლეკვებისთვის, კნუტებისთვის და მგრძნობიარე კანის მქონე ზრდასრულებისთვის.",
        "size": "500 ml",
        "price": 56.00,
        "tags": ["shampoo", "puppy", "kitten", "italian"],
    },
    {
        "slug": "tauro-pro-line-volume-spray",
        "name": "Tauro Pro Line Volume Boost Spray",
        "name_ka": "Tauro Pro Line ბეწვის მოცულობის სპრეი",
        "brand": "Tauro Pro Line",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "Lithuanian leave-in spray that adds lift and texture to fine coats. Great for show grooming and everyday styling.",
        "description_ka": "ლიეტუვური სპრეი თხელ ბეწვს მოცულობასა და ტექსტურას მატებს. შესანიშნავია გამოფენისთვის და ყოველდღიური მოვლისთვის.",
        "size": "250 ml",
        "price": 45.00,
        "tags": ["spray", "grooming", "volume"],
    },
    {
        "slug": "tauro-pro-line-volume-shampoo",
        "name": "Tauro Pro Line Hair Growth Shampoo",
        "name_ka": "Tauro Pro Line ბეწვის ზრდის შამპუნი",
        "brand": "Tauro Pro Line",
        "pet_type": "both",
        "image": IMG["shampoo"],
        "description": "Stimulates the hair follicle with botanical extracts. Use 1–2× per week to encourage faster, healthier coat growth.",
        "description_ka": "ბოტანიკური ექსტრაქტებით ბეწვის ფოლიკულის სტიმულირება. გამოიყენეთ კვირაში 1–2-ჯერ უფრო სწრაფი და ჯანსაღი ბეწვის ზრდისთვის.",
        "size": "250 ml · 1000 ml",
        "price": 49.00,
        "tags": ["shampoo", "grooming", "hair-growth"],
    },
    {
        "slug": "botaniqa-groom-it-bubble-gum",
        "name": "Botaniqa Groom-It Bubble Gum Shampoo",
        "name_ka": "Botaniqa Groom-It საღეჭი რეზინის შამპუნი",
        "brand": "Botaniqa",
        "pet_type": "both",
        "image": IMG["shampoo"],
        "description": "Polish-made shampoo with a playful bubble-gum fragrance. Concentrated 1:5 — economical for high-volume grooming.",
        "description_ka": "პოლონური წარმოების შამპუნი თამაშური საღეჭი რეზინის სურნელით. კონცენტრირებული 1:5 — ეკონომიური დიდი მოცულობით მუშაობისთვის.",
        "size": "473 ml",
        "price": 35.00,
        "tags": ["shampoo", "fragrance", "concentrated"],
    },
    {
        "slug": "isb-talc-perfume",
        "name": "ISB Talc Perfume Finishing Spray",
        "name_ka": "ISB Talc Perfume დასასრულებელი სპრეი",
        "brand": "Iv San Bernard",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "Long-lasting Italian fragrance spray with the classic talc bouquet. Applied to a dry coat for a freshly groomed finish.",
        "description_ka": "გრძელვადიანი იტალიური სურნელოვანი სპრეი კლასიკური ტალკის ბუკეტით. გამოიყენება მშრალ ბეწვზე გადარეცხვის შემდეგ.",
        "size": "150 ml",
        "price": 43.00,
        "tags": ["spray", "fragrance"],
    },
    {
        "slug": "isb-do-it-yourself-secco-shampoo",
        "name": "ISB Do It Yourself Secco Dry Shampoo",
        "name_ka": "ISB Do It Yourself Secco მშრალი შამპუნი",
        "brand": "Iv San Bernard",
        "pet_type": "both",
        "image": IMG["shampoo"],
        "description": "Foaming dry shampoo for between baths. No rinsing required — apply, massage in and towel out for a quick refresh.",
        "description_ka": "ქაფიანი მშრალი შამპუნი ბანაობას შორის გამოყენებისთვის. შლაპვა არ სჭირდება — დაიტანეთ, ხელით გაასწორეთ და პირსახოცით გადასწმინდეთ.",
        "size": "200 ml",
        "price": 54.00,
        "tags": ["dry-shampoo", "no-rinse"],
    },
    {
        "slug": "tauro-mixing-bottle-1l",
        "name": "Tauro Pro Line Mixing Bottle",
        "name_ka": "Tauro Pro Line გასაზავებელი ბოთლი",
        "brand": "Tauro Pro Line",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "1-litre dilution bottle with measured graduations for accurate shampoo-to-water ratios. Saves product and consistency.",
        "description_ka": "1-ლიტრიანი გასაზავებელი ბოთლი გრადუსაციით ზუსტი შამპუნი-წყლის თანაფარდობისთვის. ეკონომიკურია და უზრუნველყოფს თანმიმდევრულობას.",
        "size": "1000 ml",
        "price": 24.00,
        "tags": ["accessory", "grooming-tool"],
    },
    {
        "slug": "smartpaw-paw-balm",
        "name": "SmartPaw Paw Balm — Winter Protection",
        "name_ka": "SmartPaw თათის მალამო — ზამთრის დაცვა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "Beeswax and shea-butter balm that protects paw pads from salt, ice and rough pavement. Apply before walks.",
        "description_ka": "ფუტკრის ცვილისა და ში-კარაქის მალამო, რომელიც იცავს თათის ბალიშებს მარილისგან, ყინულისგან და უხეში ფეხსალაროებისგან. წაუსვით სასეირნოდ გასვლამდე.",
        "size": "60 g",
        "price": 24.00,
        "tags": ["balm", "paw-care", "winter"],
    },
    {
        "slug": "smartpaw-dental-wipes",
        "name": "SmartPaw Dental Wipes — Mint",
        "name_ka": "SmartPaw სტომატოლოგიური ხელსახოცები — პიტნა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["wipes"],
        "description": "Textured fingertip wipes that gently remove plaque and freshen breath without brushing. 30 wipes per pack.",
        "description_ka": "ტექსტურირებული თითის ხელსახოცები, რომლებიც ნაზად აშორებენ ნადებს და ანახლებენ სუნთქვას ჯაგრისის გარეშე. 30 ცალი შეფუთვაში.",
        "size": "30 wipes",
        "price": 18.50,
        "tags": ["dental", "wipes", "no-brush"],
    },
    {
        "slug": "smartpaw-ear-cleanser",
        "name": "SmartPaw Gentle Ear Cleanser",
        "name_ka": "SmartPaw ნაზი საყურე გამწმენდი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["ear_drops"],
        "description": "Alcohol-free ear cleanser with chamomile. Loosens wax and reduces yeast build-up. Vet-formulated, safe for weekly use.",
        "description_ka": "ალკოჰოლის გარეშე საყურე გამწმენდი გვირილით. ხსნის ცვილს და ამცირებს საფუარის დაგროვებას. ვეტერინარების ფორმულა — უსაფრთხო კვირაში ერთხელ გამოყენებისთვის.",
        "size": "100 ml",
        "price": 22.00,
        "tags": ["ear-care", "cleanser"],
    },
    {
        "slug": "smartpaw-deshedding-brush",
        "name": "SmartPaw De-Shedding Brush",
        "name_ka": "SmartPaw ბეწვის გადასაცლელი ჯაგრისი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["brush"],
        "description": "Curved stainless-steel undercoat rake that reaches the undercoat without nicking the skin. Reduces shedding by up to 90%.",
        "description_ka": "მოღუნული უჟანგავი ფოლადის ჯაგრისი, რომელიც აღწევს ქვედა ბეწვამდე კანის დაზიანების გარეშე. ბეწვის გადაცვენას ამცირებს 90%-მდე.",
        "size": "Standard",
        "price": 39.00,
        "tags": ["brush", "deshedding", "grooming-tool"],
        "featured": True,
    },
    {
        "slug": "smartpaw-litter-pellets",
        "name": "SmartPaw Pine Litter Pellets",
        "name_ka": "SmartPaw ფიჭვის ხის გრანულირებული ქვიშა",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["litter"],
        "description": "Natural pine pellets that absorb up to 4× their weight and neutralise odour through fresh forest scent. Biodegradable and dust-free.",
        "description_ka": "ბუნებრივი ფიჭვის გრანულები, რომლებიც შთანთქავენ თავიანთ წონაზე 4-ჯერ მეტს და ბუნებრივი ტყის სუნით ანეიტრალებენ სუნებს. ბიოდეგრადირებადი და მტვრის გარეშე.",
        "size": "5 L · 15 L",
        "price": 28.00,
        "tags": ["litter", "cat", "natural"],
    },
    {
        "slug": "smartpaw-cologne-spray",
        "name": "SmartPaw Pet Cologne — Fresh Linen",
        "name_ka": "SmartPaw სასურნელო სპრეი — სუფთა თეთრეული",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "Light, alcohol-free pet cologne with a clean fresh-linen scent. Perfect for the days between baths.",
        "description_ka": "მსუბუქი, ალკოჰოლის გარეშე სასურნელო სპრეი ცხოველებისთვის სუფთა თეთრეულის სურნელით. იდეალურია ბანაობებს შორის გასარეცხად.",
        "size": "120 ml",
        "price": 26.00,
        "tags": ["cologne", "fragrance"],
    },
    {
        "slug": "smartpaw-puppy-wipes",
        "name": "SmartPaw Puppy & Kitten Cleaning Wipes",
        "name_ka": "SmartPaw გასაწმენდი ხელსახოცები ლეკვებისთვის და კნუტებისთვის",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["wipes"],
        "description": "Hypoallergenic, fragrance-free cleansing wipes for paws, faces and bottoms. 80 large wipes per resealable tub.",
        "description_ka": "ჰიპოალერგენული, სურნელის გარეშე ხელსახოცები თათების, სახისა და ფეხების გასაწმენდად. 80 დიდი ცალი დახურულ ქილაში.",
        "size": "80 wipes",
        "price": 16.00,
        "tags": ["wipes", "puppy", "kitten"],
    },
    {
        "slug": "smartpaw-anti-tartar-gel",
        "name": "SmartPaw Anti-Tartar Dental Gel",
        "name_ka": "SmartPaw სტომატოლოგიური გელი ნადებსა და ცვილის წინააღმდეგ",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["spray"],
        "description": "Enzymatic gel that breaks down plaque and tartar with daily use. No brushing required — apply directly to teeth and gums.",
        "description_ka": "ფერმენტული გელი, რომელიც დღიური გამოყენებით შლის ნადებსა და ცვილს. ჯაგრისის გამოყენება არ სჭირდება — წაუსვით უშუალოდ კბილებსა და ღრძილებზე.",
        "size": "70 g",
        "price": 32.00,
        "tags": ["dental", "gel", "anti-tartar"],
    },
]


# ====================================================================================
# CATALOGUE -> VITAMINS (15)
# ====================================================================================
VITAMINS = [
    {
        "slug": "dr-vet-dermavet",
        "name": "Dr.Vet Dermavet — Skin & Coat",
        "name_ka": "Dr.Vet Dermavet — კანი და ბეწვი",
        "brand": "Dr.Vet",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "Serbian veterinary-grade tablets supporting healthy skin and shiny coat. Omega-3/6, biotin, zinc and B-complex in one chewable.",
        "description_ka": "სერბული ვეტერინარული ხარისხის ტაბლეტები ჯანსაღი კანისა და ბრწყინვალე ბეწვის შენარჩუნებისთვის. ომეგა-3/6, ბიოტინი, თუთია და B-კომპლექსი ერთ ცალში.",
        "size": "500 tabs",
        "price": 43.40,
        "tags": ["supplement", "skin-coat", "veterinary"],
        "featured": True,
    },
    {
        "slug": "vetapro-otipro-ear",
        "name": "VetaPro Otipro — Ear Health Drops",
        "name_ka": "VetaPro Otipro — საყურე წვეთები",
        "brand": "VetaPro",
        "pet_type": "both",
        "image": IMG["omega_oil"],
        "description": "Targeted ear-canal drops formulated to reduce inflammation and itch from yeast overgrowth. Pleasant menthol-free formula.",
        "description_ka": "მიზნობრივი წვეთები საყურე არხისთვის ანთებისა და ქავილის შესამცირებლად, რომელიც გამოწვეულია საფუარის ზრდით. სასიამოვნო, მენთოლის გარეშე ფორმულა.",
        "size": "120 ml",
        "price": 60.00,
        "tags": ["ear-care", "drops", "anti-itch"],
    },
    {
        "slug": "vetapro-skin-fur-white",
        "name": "VetaPro Skin & Fur — White Coat Formula",
        "name_ka": "VetaPro Skin & Fur — თეთრი ბეწვის ფორმულა",
        "brand": "VetaPro",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "Capsules formulated specifically for white-coated breeds. Reduces tear staining and supports a brighter, whiter coat.",
        "description_ka": "კაფსულები სპეციალურად თეთრბეწვიანი ჯიშებისთვის. ამცირებს თვალის ქვემოთ ლაქებს და ხელს უწყობს უფრო კაშკაშა, თეთრი ბეწვის შენარჩუნებას.",
        "size": "60 caps",
        "price": 50.00,
        "tags": ["supplement", "white-coat", "anti-stain"],
    },
    {
        "slug": "vetapro-cat-biotic",
        "name": "VetaPro Cat Biotic — Digestive Support",
        "name_ka": "VetaPro Cat Biotic — საჭმლის მონელების მხარდაჭერა",
        "brand": "VetaPro",
        "pet_type": "cat",
        "image": IMG["supplement_jar"],
        "description": "Multi-strain probiotic for cats. Restores gut flora after antibiotics or stress. One capsule daily — easy to hide in food.",
        "description_ka": "მრავალშტამიანი პრობიოტიკი კატებისთვის. აღადგენს ნაწლავის ფლორას ანტიბიოტიკების ან სტრესის შემდეგ. ერთი კაფსულა დღეში — საკვებში ადვილად დასამალი.",
        "size": "20 caps",
        "price": 28.00,
        "tags": ["probiotic", "cat", "digestive"],
    },
    {
        "slug": "smartpaw-omega-3-oil",
        "name": "SmartPaw Pure Omega-3 Oil",
        "name_ka": "SmartPaw წმინდა ომეგა-3 ზეთი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["omega_oil"],
        "description": "Cold-pressed Norwegian salmon oil. Pump dispenser for easy daily dosing — supports joints, skin, coat and cognition.",
        "description_ka": "ცივი წნეხის ნორვეგიული ორაგულის ზეთი. ტუმბო-დოზატორი ყოველდღიური მარტივი დოზირებისთვის — ეხმარება სახსრებს, კანს, ბეწვს და კოგნიტურ ფუნქციას.",
        "size": "300 ml",
        "price": 36.00,
        "tags": ["omega-3", "salmon-oil", "joint-support"],
        "featured": True,
    },
    {
        "slug": "smartpaw-joint-mobility",
        "name": "SmartPaw Joint Mobility — Glucosamine + MSM",
        "name_ka": "SmartPaw სახსრების მობილობა — გლუკოზამინი + MSM",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["joint_tabs"],
        "description": "Highly palatable chews with glucosamine, chondroitin and MSM. Clinical dose for active and senior dogs.",
        "description_ka": "გემრიელი საღეჭები გლუკოზამინით, ქონდროიტინითა და MSM-ით. კლინიკური დოზა აქტიური და ხანდაზმული ძაღლებისთვის.",
        "size": "60 chews",
        "price": 48.00,
        "tags": ["joint", "glucosamine", "senior"],
    },
    {
        "slug": "smartpaw-calm-mind",
        "name": "SmartPaw Calm Mind — Anxiety Support",
        "name_ka": "SmartPaw წყნარი გონება — შფოთვის შემცირება",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "L-theanine, valerian and chamomile blend that takes the edge off thunder, fireworks and travel anxiety. Non-drowsy.",
        "description_ka": "L-თეანინი, ვალერიანი და გვირილა — ნარევი, რომელიც ამცირებს ჭექა-ქუხილის, ფეიერვერკისა და მგზავრობის შფოთვას. არ იწვევს ძილს.",
        "size": "30 chews",
        "price": 34.00,
        "tags": ["calming", "anxiety", "travel"],
    },
    {
        "slug": "smartpaw-multivit-adult",
        "name": "SmartPaw Daily Multivit — Adult",
        "name_ka": "SmartPaw ყოველდღიური მულტი-ვიტამინი — ზრდასრულისთვის",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "Complete vitamin/mineral premix to fill nutritional gaps in home-cooked or kibble diets. 27 essential micronutrients.",
        "description_ka": "სრული ვიტამინი-მინერალის პრემიქსი სახლის რაციონის ან კიბლის კვების ხარვეზების შესავსებად. 27 აუცილებელი მიკროელემენტი.",
        "size": "60 tabs · 180 tabs",
        "price": 22.00,
        "tags": ["multivitamin", "daily"],
    },
    {
        "slug": "smartpaw-probiotic-blend",
        "name": "SmartPaw Probiotic Blend — 10 Strains",
        "name_ka": "SmartPaw პრობიოტიკული ნარევი — 10 შტამი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "Powder probiotic sprinkled over food. 10 strains and 5 billion CFUs per dose for healthy digestion and a strong immune system.",
        "description_ka": "ფხვნილოვანი პრობიოტიკი საკვებზე მოსაყრელად. 10 შტამი და 5 მილიარდი CFU დოზაში ჯანსაღი მონელებისა და ძლიერი იმუნური სისტემისთვის.",
        "size": "100 g",
        "price": 38.00,
        "tags": ["probiotic", "powder", "immune"],
    },
    {
        "slug": "smartpaw-puppy-growth-vit",
        "name": "SmartPaw Puppy Growth Vitamin Powder",
        "name_ka": "SmartPaw ლეკვის ზრდის ვიტამინური ფხვნილი",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["supplement_jar"],
        "description": "Balanced calcium, phosphorus and vitamin D3 powder for puppies in the critical 2–9 month growth window.",
        "description_ka": "დაბალანსებული კალციუმის, ფოსფორისა და D3 ვიტამინის ფხვნილი 2–9 თვის კრიტიკული ზრდის ფანჯრის ლეკვებისთვის.",
        "size": "150 g",
        "price": 24.00,
        "tags": ["puppy", "growth", "calcium"],
    },
    {
        "slug": "smartpaw-immune-boost-chews",
        "name": "SmartPaw Immune Boost — Elderberry Chews",
        "name_ka": "SmartPaw იმუნური მხარდაჭერა — შავი ბუსუსის საღეჭები",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["joint_tabs"],
        "description": "Elderberry, mushroom complex and vitamin C in a chicken-flavoured chew. Excellent during seasonal changes.",
        "description_ka": "შავი ბუსუსი, სოკოს კომპლექსი და C ვიტამინი ქათმის გემოს მქონე საღეჭში. შესანიშნავია სეზონური ცვლილებების დროს.",
        "size": "60 chews",
        "price": 32.00,
        "tags": ["immune", "elderberry", "chews"],
    },
    {
        "slug": "smartpaw-uti-cranberry",
        "name": "SmartPaw UTI Defence — Cranberry & D-Mannose",
        "name_ka": "SmartPaw საშარდე გზების დაცვა — შავთუხტი და D-მანოზა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["supplement_jar"],
        "description": "Cranberry extract and D-mannose blend supporting urinary tract health. Especially helpful for senior cats and small dogs.",
        "description_ka": "შავთუხტის ექსტრაქტისა და D-მანოზის ნარევი საშარდე გზების ჯანმრთელობისთვის. განსაკუთრებით სასარგებლოა ხანდაზმული კატებისა და მცირე ძაღლებისთვის.",
        "size": "60 caps",
        "price": 36.00,
        "tags": ["urinary", "cranberry"],
    },
    {
        "slug": "smartpaw-dental-water-additive",
        "name": "SmartPaw Dental Water Additive",
        "name_ka": "SmartPaw წყლის სტომატოლოგიური დანამატი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["omega_oil"],
        "description": "Tasteless water additive that helps reduce plaque, tartar and bad breath with every sip. 30-day supply.",
        "description_ka": "გემოს გარეშე წყლის დანამატი, რომელიც ეხმარება ნადებების, ცვილისა და უსიამოვნო სუნის შემცირებაში ყოველი წყლის ყლუპში. 30 დღის მარაგი.",
        "size": "500 ml",
        "price": 28.00,
        "tags": ["dental", "water-additive"],
    },
    {
        "slug": "smartpaw-senior-cognitive",
        "name": "SmartPaw Senior Cognitive Support",
        "name_ka": "SmartPaw ხანდაზმული მეგობრის კოგნიტური მხარდაჭერა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["joint_tabs"],
        "description": "DHA, MCT oil and antioxidants formulated to support brain function in dogs and cats over 8 years old.",
        "description_ka": "DHA, MCT ზეთი და ანტიოქსიდანტები 8 წელზე უფროსი ძაღლებისა და კატების ტვინის ფუნქციის მხარდასაჭერად.",
        "size": "60 chews",
        "price": 44.00,
        "tags": ["senior", "cognitive", "dha"],
    },
    {
        "slug": "smartpaw-hairball-soft-chews",
        "name": "SmartPaw Hairball Soft Chews — Cat",
        "name_ka": "SmartPaw ბეწვის ბურთულების რბილი საღეჭები — კატებისთვის",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["supplement_jar"],
        "description": "Salmon-flavoured soft chews with psyllium fibre and slippery elm — gently help cats pass swallowed hair.",
        "description_ka": "ორაგულის გემოს რბილი საღეჭები ფსილიუმის ბოჭკოთი — ნაზად ეხმარება კატებს გაყლაპული ბეწვის გასულობაში.",
        "size": "60 chews",
        "price": 26.00,
        "tags": ["cat", "hairball", "chews"],
    },
]


# ====================================================================================
# SPECIALS -> TOYS & ACCESSORIES (15)
# ====================================================================================
TOYS = [
    {
        "slug": "hunter-collar-convenience-plastic",
        "name": "HUNTER Collar Convenience — Plastic Buckle",
        "name_ka": "HUNTER საყელო Convenience — პლასტიკური ბალთით",
        "brand": "HUNTER",
        "pet_type": "dog",
        "image": IMG["collar"],
        "description": "German-engineered weather-resistant collar with a quick-release plastic buckle. Reflective trim for evening walks.",
        "description_ka": "გერმანული ინჟინერიის წყალგამძლე საყელო სწრაფი ღაბაშის პლასტიკური ბალთით. ამრეკლავი ზოლი საღამოს სასეირნოდ.",
        "size": "S · M · L",
        "price": 41.00,
        "tags": ["collar", "reflective"],
    },
    {
        "slug": "hunter-t-leash-convenience",
        "name": "HUNTER T-Leash Convenience 20/200",
        "name_ka": "HUNTER T-Leash Convenience 20/200",
        "brand": "HUNTER",
        "pet_type": "dog",
        "image": IMG["leash"],
        "description": "2-metre webbed lead with a soft padded handle. The matching T-clip closes silently — no metallic clatter.",
        "description_ka": "2-მეტრიანი ლენტიანი საქელე რბილი მოპირკეთებული სახელურით. შესაბამისი T-კლიპი იხურება უხმოდ — ლითონის ბრახუნის გარეშე.",
        "size": "20mm × 200cm",
        "price": 100.00,
        "tags": ["leash", "everyday"],
    },
    {
        "slug": "smartpaw-bungee-leash",
        "name": "SmartPaw Shock-Absorbing Bungee Leash",
        "name_ka": "SmartPaw შოკის შთამნთქმელი საქელე",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["leash"],
        "description": "Elasticated leash that absorbs sudden lunges — kinder on your shoulder and your dog's neck. Reflective stitching.",
        "description_ka": "ელასტიური საქელე, რომელიც შთანთქავს უეცარ წევებს — უფრო ნაზია მხრისთვის და ძაღლის კისრისთვის. ამრეკლავი ნაკერი.",
        "size": "1.2m – 1.8m",
        "price": 36.00,
        "tags": ["leash", "shock-absorbing"],
        "featured": True,
    },
    {
        "slug": "smartpaw-tug-rope-large",
        "name": "SmartPaw Cotton Tug Rope — Large",
        "name_ka": "SmartPaw ბამბის თამაში — დიდი",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["chew_toy"],
        "description": "Triple-knotted natural cotton rope. Excellent for two-dog play, tug-of-war and dental flossing as they chew.",
        "description_ka": "სამმაგი კვანძი ბუნებრივი ბამბის თოკით. შესანიშნავია ორი ძაღლის თამაშისთვის, თოკის ბრძოლისა და ღეჭვის დროს კბილების გასუფთავებისთვის.",
        "size": "45 cm",
        "price": 14.00,
        "tags": ["toy", "tug", "rope"],
    },
    {
        "slug": "smartpaw-kong-style-bouncer",
        "name": "SmartPaw Treat-Holder Bouncer",
        "name_ka": "SmartPaw გასახტომი სამადლი",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["ball_toy"],
        "description": "Natural rubber treat-stuffer in our signature beehive shape. Bounces unpredictably for hours of solo entertainment.",
        "description_ka": "ბუნებრივი რეზინის სამადლი ჩვენი დამახასიათებელი ფიჭის ფორმით. გასახტომი არანდომულად — საათობით გასართობი ცხოველს მარტოს.",
        "size": "M · L",
        "price": 32.00,
        "tags": ["toy", "enrichment", "treat-dispenser"],
    },
    {
        "slug": "smartpaw-feather-wand",
        "name": "SmartPaw Interactive Feather Wand",
        "name_ka": "SmartPaw ინტერაქტიული ბუმბულის ჯოხი",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["chew_toy"],
        "description": "Retractable wand toy with replaceable feather and crinkle attachments. Engages a cat's predatory instinct.",
        "description_ka": "ჩასაშლელი ჯოხის სათამაშო შესაცვლელი ბუმბულითა და ხრიოკი დანამატებით. აქტიურდება კატის მტაცებლური ინსტინქტი.",
        "size": "Standard",
        "price": 18.00,
        "tags": ["toy", "cat", "wand"],
    },
    {
        "slug": "smartpaw-cat-tunnel-3way",
        "name": "SmartPaw Crinkle Cat Tunnel — 3-Way",
        "name_ka": "SmartPaw კატის გვირაბი — 3-გასასვლელიანი",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["chew_toy"],
        "description": "Collapsible Y-shaped tunnel with crinkle material and a peek hole. Folds flat for storage.",
        "description_ka": "ჩასაშლელი Y-ფორმის გვირაბი ხრიოკი მასალითა და სამხედვრო ხვრელით. ბრტყლად იკეცება შენახვისთვის.",
        "size": "120 cm",
        "price": 42.00,
        "tags": ["toy", "cat", "tunnel"],
    },
    {
        "slug": "smartpaw-orthopedic-bed",
        "name": "SmartPaw Orthopedic Memory-Foam Bed",
        "name_ka": "SmartPaw ორთოპედიული მეხსიერების ქაფის საწოლი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["bed"],
        "description": "5-cm memory foam base with a bolstered headrest. Removable, machine-washable cover. Ideal for senior pets and post-surgery recovery.",
        "description_ka": "5-სმ მეხსიერების ქაფის ფუძე გაძლიერებული თავსაბურავით. გასახდელი, სამრეცხო მანქანაში გასარეცხი ქისა. იდეალურია ხანდაზმული ცხოველებისა და ოპერაციის შემდგომი აღდგენისთვის.",
        "size": "S · M · L · XL",
        "price": 95.00,
        "tags": ["bed", "orthopedic", "memory-foam"],
        "featured": True,
    },
    {
        "slug": "smartpaw-donut-bed",
        "name": "SmartPaw Calming Donut Bed — Faux Fur",
        "name_ka": "SmartPaw დამამშვიდებელი დონატის საწოლი — ხელოვნური ბეწვი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["bed"],
        "description": "Round 'donut' bed with raised faux-fur rim. Mimics the security of being curled up against a litter-mate.",
        "description_ka": "მრგვალი 'დონატის' საწოლი ამაღლებული ხელოვნური ბეწვის კიდით. ბაძავს ერთად დაბრუნებული ნაშიერების უსაფრთხოების შეგრძნებას.",
        "size": "50 cm · 70 cm · 90 cm",
        "price": 75.00,
        "tags": ["bed", "calming", "faux-fur"],
    },
    {
        "slug": "smartpaw-travel-carrier",
        "name": "SmartPaw Airline-Approved Travel Carrier",
        "name_ka": "SmartPaw ავიაკომპანიის სტანდარტის გადამზიდი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["carrier"],
        "description": "IATA-compliant under-seat carrier with mesh ventilation on three sides. Padded shoulder strap and seatbelt loop.",
        "description_ka": "IATA-სტანდარტის სავარძლის ქვეშ მოთავსებადი გადამზიდი ბადისებური ვენტილაციით სამი მხრიდან. რბილი მხრის ღვედი და ღვედის ხვრელი.",
        "size": "Small · Medium",
        "price": 110.00,
        "tags": ["carrier", "travel", "airline"],
    },
    {
        "slug": "smartpaw-slow-feed-bowl",
        "name": "SmartPaw Slow-Feeder Bowl",
        "name_ka": "SmartPaw ნელი კვების ჯამი",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["bowl"],
        "description": "Maze-pattern bowl that slows eating by up to 10×. Prevents bloat and stimulates the brain at every meal.",
        "description_ka": "ლაბირინთის ფორმის ჯამი, რომელიც ანელებს ჭამას 10-ჯერ. ხელს უშლის გაბერვას და ასტიმულირებს ტვინს ყოველ კვებაზე.",
        "size": "Medium · Large",
        "price": 28.00,
        "tags": ["bowl", "slow-feeder", "enrichment"],
    },
    {
        "slug": "smartpaw-ceramic-bowl-set",
        "name": "SmartPaw Ceramic Bowl Set — Twin",
        "name_ka": "SmartPaw კერამიკული ჯამების ნაკრები — წყვილი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["bowl"],
        "description": "Heavy ceramic twin-bowl set with a bamboo stand. Dishwasher safe and resistant to tipping during enthusiastic mealtimes.",
        "description_ka": "მძიმე კერამიკული წყვილი ჯამების ნაკრები ბამბუკის სტენდით. ჭურჭლის სარეცხ მანქანაში გასარეცხი და ენთუზიასტური კვების დროს გადახრის მდგრადი.",
        "size": "Small · Medium",
        "price": 38.00,
        "tags": ["bowl", "ceramic", "set"],
    },
    {
        "slug": "smartpaw-puzzle-feeder",
        "name": "SmartPaw Slide Puzzle Feeder",
        "name_ka": "SmartPaw გასასრიალებელი თავსატეხის კვებიდანი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["ball_toy"],
        "description": "Five-level puzzle that hides kibble under sliders and rotating blocks. Increase difficulty as your pet learns each level.",
        "description_ka": "ხუთდონიანი თავსატეხი, რომელიც მალავს კიბლს გასასრიალებლების და მბრუნავი ბლოკების ქვეშ. გაართულეთ, როცა ცხოველი თითოეულ დონეს ისწავლის.",
        "size": "Standard",
        "price": 45.00,
        "tags": ["puzzle", "enrichment", "feeder"],
    },
    {
        "slug": "smartpaw-clicker-trainer",
        "name": "SmartPaw Clicker Trainer + Wrist Strap",
        "name_ka": "SmartPaw წკაპუნა + მაჯის ღვედი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["chew_toy"],
        "description": "Soft-press clicker (no jarring metallic snap) with adjustable wrist strap. Crystal-clear marker for fast positive-reinforcement training.",
        "description_ka": "რბილი დაჭერის წკაპუნა (ხმოვანი ლითონის ჭრიალის გარეშე) რეგულირებადი მაჯის ღვედით. გასაგები მარკერი დადებითი დამხარისხებითი ვარჯიშისთვის.",
        "size": "Standard",
        "price": 12.00,
        "tags": ["training", "clicker"],
    },
    {
        "slug": "smartpaw-cat-scratcher-board",
        "name": "SmartPaw Cat Scratcher Board with Catnip",
        "name_ka": "SmartPaw კატის საფხეკი დაფა კატნიპით",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["chew_toy"],
        "description": "Double-sided corrugated cardboard scratcher pre-loaded with potent catnip. Refill packs available.",
        "description_ka": "ორმხრივი დაჭიმული მუყაოს საფხეკი, წინასწარ ნაერთი ძლიერი კატნიპით. დანამატის შესაცვლელი პაკეტები ხელმისაწვდომია.",
        "size": "Standard",
        "price": 16.00,
        "tags": ["scratcher", "cat", "catnip"],
    },
]


# ====================================================================================
# SPECIALS -> INNOVATION & TECH (15)
# ====================================================================================
TECH = [
    {
        "slug": "smartpaw-auto-feeder-app",
        "name": "SmartPaw Wi-Fi Auto Feeder — App Controlled",
        "name_ka": "SmartPaw Wi-Fi ავტომატური კვებიდანი — აპლიკაციით მართვა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["smart_feeder"],
        "description": "Schedule up to 6 daily meals or feed remotely from your phone. 4-litre hopper with twin desiccant compartments to keep kibble fresh.",
        "description_ka": "დაგეგმეთ 6-მდე ყოველდღიური კვება ან აჭამეთ დისტანციურად ტელეფონიდან. 4-ლიტრიანი კონტეინერი ორმაგი მშრალი ჰიგროსკოპული საკნებით კიბლის სიახლის შესანარჩუნებლად.",
        "size": "4 L · WiFi 2.4 GHz",
        "price": 240.00,
        "tags": ["smart-feeder", "wifi", "app-controlled"],
        "featured": True,
    },
    {
        "slug": "smartpaw-gps-tracker-collar",
        "name": "SmartPaw GPS + LTE Tracker Collar",
        "name_ka": "SmartPaw GPS + LTE მძებნელი საყელო",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["gps_tracker"],
        "description": "Real-time GPS location with no range limit. LTE-M built-in. Geofence alerts, activity tracking and a 7-day battery.",
        "description_ka": "რეალურ დროში GPS მდებარეობა შეუზღუდავი დიაპაზონით. ჩაშენებული LTE-M. გეო-ღობის შეტყობინებები, აქტივობის თვალყურის დევნება და 7-დღიანი ბატარეა.",
        "size": "Collar · 25 g",
        "price": 280.00,
        "tags": ["gps", "tracker", "lte"],
        "featured": True,
    },
    {
        "slug": "smartpaw-pet-camera-treat",
        "name": "SmartPaw Pet Camera with Treat Toss",
        "name_ka": "SmartPaw ცხოველის კამერა საღოვის გადასროლით",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["pet_camera"],
        "description": "1080p HD camera with two-way audio and a remote-controlled treat dispenser. Night vision, motion alerts and bark detection.",
        "description_ka": "1080p HD კამერა ორმხრივი აუდიოთი და დისტანციური სამადლის გადასაგდები მექანიზმით. ღამის ხედვა, მოძრაობის შეტყობინებები და ყეფის გამოვლენა.",
        "size": "Wi-Fi · 30 treats",
        "price": 195.00,
        "tags": ["camera", "treat-toss", "monitor"],
    },
    {
        "slug": "smartpaw-self-clean-litter-box",
        "name": "SmartPaw Self-Cleaning Litter Box — Cube",
        "name_ka": "SmartPaw თვითგამწმენდი ტუალეტი — კუბი",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["smart_litter"],
        "description": "Sensor-activated raking system that scoops 30 seconds after use. App tracks each visit and weight — early warning for urinary issues.",
        "description_ka": "სენსორებით აქტიური სიგრძივი სისტემა, რომელიც ასუფთავებს ცხოველის გასვლიდან 30 წამში. აპლიკაცია ადევნებს თვალყურს ყოველ ვიზიტს და წონას — საშარდე პრობლემების ადრეული გაფრთხილება.",
        "size": "55 × 55 × 65 cm",
        "price": 450.00,
        "tags": ["smart", "litter-box", "self-cleaning"],
    },
    {
        "slug": "smartpaw-water-fountain-uv",
        "name": "SmartPaw UV-Sterilising Water Fountain",
        "name_ka": "SmartPaw UV-სტერილიზებადი წყლის შადრევანი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["water_fountain"],
        "description": "3-litre ceramic fountain with built-in UV-C lamp and triple filtration. Encourages drinking and inhibits bacterial growth.",
        "description_ka": "3-ლიტრიანი კერამიკული შადრევანი ჩაშენებული UV-C ნათურით და სამმაგი ფილტრაციით. ხელს უწყობს წყლის სმას და აფერხებს ბაქტერიების ზრდას.",
        "size": "3 L",
        "price": 130.00,
        "tags": ["fountain", "uv", "hydration"],
    },
    {
        "slug": "smartpaw-activity-tracker",
        "name": "SmartPaw Activity & Sleep Tracker",
        "name_ka": "SmartPaw აქტივობისა და ძილის ტრეკერი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["gps_tracker"],
        "description": "Light-weight clip-on tag that attaches to any collar. Tracks steps, sleep quality and calories burned. Vet-readable trend reports.",
        "description_ka": "მსუბუქი მისამაგრებელი ტეგი, რომელიც ნებისმიერ საყელოს ერგება. ადევნებს თვალყურს ნაბიჯებს, ძილის ხარისხს და დაწვულ კალორიებს. ვეტერინარისთვის გასაგები ანგარიშები.",
        "size": "15 g",
        "price": 95.00,
        "tags": ["tracker", "activity", "sleep"],
    },
    {
        "slug": "smartpaw-smart-door",
        "name": "SmartPaw Microchip Smart Door",
        "name_ka": "SmartPaw მიკროჩიპით სამართავი კარი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["smart_feeder"],
        "description": "RFID/microchip-locked pet door that only opens for your registered pets. Curfew schedule keeps intruders out at night.",
        "description_ka": "RFID/მიკროჩიპით დაცული კარი ცხოველებისთვის, რომელიც იხსნება მხოლოდ თქვენი დარეგისტრირებული ცხოველებისთვის. ღამის რეჟიმი არ უშვებს უცხო ცხოველებს.",
        "size": "S · M · L",
        "price": 320.00,
        "tags": ["smart-door", "microchip"],
    },
    {
        "slug": "smartpaw-collar-led",
        "name": "SmartPaw Rechargeable LED Collar",
        "name_ka": "SmartPaw დატენადი LED საყელო",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["collar"],
        "description": "USB-rechargeable collar with three modes — steady, slow blink and fast blink. Visible from 400 metres for safe night walks.",
        "description_ka": "USB-დატენადი საყელო სამი რეჟიმით — მუდმივი, ნელი ციმციმი და სწრაფი ციმციმი. ხილული 400 მეტრიდან უსაფრთხო ღამის სასეირნოდ.",
        "size": "S · M · L",
        "price": 38.00,
        "tags": ["collar", "led", "safety"],
    },
    {
        "slug": "smartpaw-bark-anti-trainer",
        "name": "SmartPaw Ultrasonic Anti-Bark Trainer",
        "name_ka": "SmartPaw ულტრაბგერითი ანტი-ყეფის ვარჯიში",
        "brand": "SmartPaw",
        "pet_type": "dog",
        "image": IMG["gps_tracker"],
        "description": "Humane ultrasonic device emits a high-pitch tone (inaudible to humans) when triggered by excessive barking. Adjustable sensitivity.",
        "description_ka": "ჰუმანური ულტრაბგერითი მოწყობილობა, რომელიც გამოსცემს მაღალი ტონის ხმას (ადამიანისთვის გაუგებარს), როცა ცხოველი ზედმეტად ყეფს. რეგულირებადი მგრძნობელობა.",
        "size": "Compact",
        "price": 65.00,
        "tags": ["training", "anti-bark", "ultrasonic"],
    },
    {
        "slug": "smartpaw-cooling-mat-gel",
        "name": "SmartPaw Self-Cooling Gel Mat",
        "name_ka": "SmartPaw თვითგამაგრილებელი გელის ხალიჩა",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["bed"],
        "description": "Pressure-activated cooling gel that drops surface temperature by 4–6°C. No water, freezer or electricity required.",
        "description_ka": "წნევით აქტიური გამაგრილებელი გელი, რომელიც ზედაპირის ტემპერატურას აქვეითებს 4–6°C-ით. წყლის, საყინულის ან ელექტრო ენერგიის გარეშე.",
        "size": "M · L · XL",
        "price": 55.00,
        "tags": ["cooling-mat", "summer"],
    },
    {
        "slug": "smartpaw-smart-bowl-scale",
        "name": "SmartPaw Smart Bowl with Scale",
        "name_ka": "SmartPaw ჭკვიანი ჯამი წონისა ხელით",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["bowl"],
        "description": "Bowl with a built-in scale that auto-logs how much your pet eats. Pairs with the SmartPaw app for weight management.",
        "description_ka": "ჩაშენებული წონის სასწორი ჯამში, რომელიც ავტომატურად აღრიცხავს რამდენი ჭამა ცხოველმა. ერთიანდება SmartPaw აპლიკაციასთან წონის მართვისთვის.",
        "size": "Medium",
        "price": 75.00,
        "tags": ["smart-bowl", "scale", "app"],
    },
    {
        "slug": "smartpaw-pet-vacuum-grooming",
        "name": "SmartPaw Vacuum Grooming Kit — 5-in-1",
        "name_ka": "SmartPaw საფხეკი მტვერსასრუტი — 5-1-ში",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["brush"],
        "description": "Five interchangeable heads (de-shed, clipper, nozzle, comb, brush) with a 2.5-litre suction canister. Up to 99% of loose hair captured.",
        "description_ka": "ხუთი შესაცვლელი თავი (გადასაცლელი, საკრეჭი, ცხვირი, სავარცხელი, ჯაგრისი) 2.5-ლიტრიანი ასაწოვი კონტეინერით. გადაცემული ბეწვის 99%-მდე იჭერს.",
        "size": "2.5 L · 5 attachments",
        "price": 235.00,
        "tags": ["vacuum", "grooming", "deshedding"],
    },
    {
        "slug": "smartpaw-uv-sanitiser-box",
        "name": "SmartPaw UV-C Toy Sanitiser Box",
        "name_ka": "SmartPaw UV-C სათამაშოების სტერილიზაციის ყუთი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["smart_feeder"],
        "description": "Drop in toys, leashes and bowls — 99.9% of bacteria killed in a 10-minute UV-C cycle. No chemicals, no residue.",
        "description_ka": "ჩააგდეთ სათამაშოები, საქელეები და ჯამები — ბაქტერიების 99.9% იხოცება 10-წუთიანი UV-C ციკლით. ქიმიკატების და ნარჩენების გარეშე.",
        "size": "5 L",
        "price": 120.00,
        "tags": ["uv-c", "sanitiser"],
    },
    {
        "slug": "smartpaw-temperature-monitor",
        "name": "SmartPaw Cabin & Car Temperature Monitor",
        "name_ka": "SmartPaw სალონისა და მანქანის ტემპერატურის მონიტორი",
        "brand": "SmartPaw",
        "pet_type": "both",
        "image": IMG["pet_camera"],
        "description": "Wi-Fi sensor that pings your phone the moment cabin temperature crosses a safe threshold. Essential for summer drives.",
        "description_ka": "Wi-Fi სენსორი, რომელიც ტელეფონს უგზავნის შეტყობინებას, როცა სალონის ტემპერატურა უსაფრთხო ზღვარს გადააჭარბებს. აუცილებელია ზაფხულის მოგზაურობებისთვის.",
        "size": "Wi-Fi · Battery",
        "price": 85.00,
        "tags": ["monitor", "safety", "summer"],
    },
    {
        "slug": "smartpaw-laser-toy-auto",
        "name": "SmartPaw Auto-Laser Play Tower",
        "name_ka": "SmartPaw ავტომატური ლაზერული თამაშის კოშკი",
        "brand": "SmartPaw",
        "pet_type": "cat",
        "image": IMG["chew_toy"],
        "description": "Random-pattern laser projector with three speed settings and a 15-minute auto-off timer. Saves you from being the entertainer.",
        "description_ka": "შემთხვევითი ნიმუშის ლაზერული პროექტორი სამი სიჩქარის რეჟიმით და 15-წუთიანი ავტომატური გამოყვანის ტაიმერით. გათავისუფლებთ მუდმივი თამაშისგან.",
        "size": "Battery · USB-C",
        "price": 48.00,
        "tags": ["laser", "auto-toy", "cat"],
    },
]


# ====================================================================================
# SPECIALS -> SERVICES (15)
# ====================================================================================
SERVICES = [
    {
        "slug": "service-grooming-full-spa",
        "name": "Full Grooming Spa — Bath, Cut & Style",
        "name_ka": "სრული გრუმინგის სპა — ბანვა, შეჭრა და სტილი",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_grooming"],
        "description": "90-minute spa: bath, breed-specific cut, nail trim, ear cleaning and a finishing perfume. Includes a free post-groom photo.",
        "description_ka": "90-წუთიანი სპა: ბანვა, ჯიშის შესაბამისი შეჭრა, ფრჩხილების მოჭრა, ყურების გასუფთავება და დასარულებელი სურნელი. მოიცავს უფასო შემდგომ ფოტოს.",
        "size": "90 min",
        "price": 90.00,
        "tags": ["service", "grooming", "spa"],
        "featured": True,
    },
    {
        "slug": "service-grooming-express",
        "name": "Express Wash & Tidy — 45 min",
        "name_ka": "სწრაფი ბანვა და მოწესრიგება — 45 წთ",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_grooming"],
        "description": "Quick refresh: bath, blow-dry, nail clip and sanitary trim. In-and-out in 45 minutes — perfect between full grooms.",
        "description_ka": "სწრაფი განახლება: ბანვა, ჩამშრობი, ფრჩხილების შეჭრა და სანიტარული შესწორება. შესვლა-გასვლა 45 წუთში — შესანიშნავია სრულ გრუმინგებს შორის.",
        "size": "45 min",
        "price": 45.00,
        "tags": ["service", "grooming", "express"],
    },
    {
        "slug": "service-deshedding-treatment",
        "name": "De-Shedding Treatment — Reduces 90% Shedding",
        "name_ka": "ბეწვის გადასატანი მკურნალობა — 90%-ით ამცირებს",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_grooming"],
        "description": "Deep undercoat-rake treatment + high-velocity blow-out. Recommended monthly for double-coated breeds. Significant reduction in shed hair at home for 4+ weeks.",
        "description_ka": "ღრმა ქვედა ბეწვის გადასატანი მკურნალობა + მაღალი სიჩქარის ჩამშრობი. რეკომენდებულია ყოველთვიურად ორმაგი ბეწვის ჯიშებისთვის. სახლში ბეწვის გადაცვენის მნიშვნელოვანი შემცირება 4+ კვირის განმავლობაში.",
        "size": "60 min",
        "price": 70.00,
        "tags": ["service", "deshedding", "grooming"],
    },
    {
        "slug": "service-nail-trim",
        "name": "Nail Trim & Paw Pad Care",
        "name_ka": "ფრჩხილების მოჭრა და თათის მოვლა",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_grooming"],
        "description": "Stress-free nail clipping with a quartz file finish. Paw pads trimmed and moisturised with our signature balm.",
        "description_ka": "სტრესის გარეშე ფრჩხილების მოჭრა და კვარცის ფაილით დასასრულება. თათის ბალიშები შეჭრილი და დატენიანებული ჩვენი დამახასიათებელი მალამოთი.",
        "size": "20 min",
        "price": 20.00,
        "tags": ["service", "nails", "paw-care"],
    },
    {
        "slug": "service-dental-cleaning",
        "name": "Awake Dental Cleaning — No Anaesthesia",
        "name_ka": "ცნობიერად სტომატოლოგია — ანესთეზიის გარეშე",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_grooming"],
        "description": "Gentle ultrasonic scaling performed by a certified hygienist. Suitable for pets with mild–moderate plaque who tolerate handling.",
        "description_ka": "ნაზი ულტრაბგერითი წმენდა, შესრულებული სერთიფიცირებული ჰიგიენისტის მიერ. შესაფერისია ცხოველებისთვის ნაკლები ან საშუალო ნადებებით, რომლებიც ითმენენ შემოწმებას.",
        "size": "45 min",
        "price": 95.00,
        "tags": ["service", "dental", "no-anaesthesia"],
    },
    {
        "slug": "service-dog-walking-30",
        "name": "Dog Walking — 30 minute solo walk",
        "name_ka": "ძაღლის სასეირნოდ გაყვანა — 30-წუთიანი ინდივიდუალური სასეირნო",
        "brand": "SmartPaw Care",
        "pet_type": "dog",
        "image": IMG["service_walking"],
        "description": "Insured, background-checked walker takes your dog out solo (no group walks). GPS-tracked route and a post-walk report.",
        "description_ka": "დაზღვეული, შემოწმებული გამყვანი თქვენს ძაღლს გაიყვანს ცალკე (ჯგუფური სასეირნოს გარეშე). GPS-მონიტორინგი მარშრუტისა და სასეირნოს შემდგომი ანგარიში.",
        "size": "30 min",
        "price": 30.00,
        "tags": ["service", "dog-walking"],
        "featured": True,
    },
    {
        "slug": "service-dog-walking-60",
        "name": "Dog Walking — 60 minute adventure walk",
        "name_ka": "ძაღლის სასეირნოდ გაყვანა — 60-წუთიანი თავგადასავალი",
        "brand": "SmartPaw Care",
        "pet_type": "dog",
        "image": IMG["service_walking"],
        "description": "An hour-long sniff-and-explore walk in nearby parks. Ideal for high-energy breeds — includes water break and shade.",
        "description_ka": "საათიანი 'საყნოსე-დასაკვირვებელი' სასეირნო ახლომდებარე პარკებში. იდეალურია მაღალენერგიული ჯიშებისთვის — მოიცავს წყლის შესვენებას და ჩრდილს.",
        "size": "60 min",
        "price": 55.00,
        "tags": ["service", "dog-walking", "adventure"],
    },
    {
        "slug": "service-training-basic-pack",
        "name": "Foundation Training — 4-Session Pack",
        "name_ka": "ფუნდამენტური ვარჯიში — 4-სესიის პაკეტი",
        "brand": "SmartPaw Care",
        "pet_type": "dog",
        "image": IMG["service_training"],
        "description": "Sit · Stay · Recall · Loose-leash walking. Four 60-minute sessions with a certified positive-reinforcement trainer.",
        "description_ka": "ჯდომა · დარჩენა · მოწოდება · გათავისუფლებული საქელით სიარული. ოთხი 60-წუთიანი სესია სერთიფიცირებული დადებითი დამხარისხებითი მწვრთნელის ხელმძღვანელობით.",
        "size": "4 × 60 min",
        "price": 280.00,
        "tags": ["service", "training", "basic"],
    },
    {
        "slug": "service-training-puppy-school",
        "name": "Puppy School — 6-Week Group Class",
        "name_ka": "ლეკვების სკოლა — 6-კვირიანი ჯგუფური კურსი",
        "brand": "SmartPaw Care",
        "pet_type": "dog",
        "image": IMG["service_training"],
        "description": "Socialisation + manners class for puppies 3–6 months. Small groups of 4 pups maximum. Vaccination records required.",
        "description_ka": "სოციალიზაცია + წესების კურსი 3–6 თვის ლეკვებისთვის. პატარა ჯგუფი მაქსიმუმ 4 ლეკვით. სავაქცინაციო ჩანაწერები საჭიროა.",
        "size": "6 × 45 min",
        "price": 220.00,
        "tags": ["service", "training", "puppy", "group"],
    },
    {
        "slug": "service-behaviour-consult",
        "name": "Behaviour Consultation — 90 min in-home",
        "name_ka": "ქცევის კონსულტაცია — 90 წთ სახლში",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_training"],
        "description": "In-home assessment for issues like resource guarding, separation anxiety or reactivity. Written behaviour plan included.",
        "description_ka": "ქცევის სახლში შეფასება ისეთი საკითხებისთვის, როგორიცაა რესურსების დაცვა, განშორების შფოთვა ან რეაქტიულობა. წერილობითი ქცევის გეგმა შედის ფასში.",
        "size": "90 min",
        "price": 150.00,
        "tags": ["service", "behaviour", "consult"],
    },
    {
        "slug": "service-vet-checkup",
        "name": "Wellness Check-Up — In-Clinic",
        "name_ka": "ჯანმრთელობის შემოწმება — კლინიკაში",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_vet"],
        "description": "Comprehensive nose-to-tail vet exam, weight check and vaccination review. Includes a printed health passport summary.",
        "description_ka": "სრულყოფილი ცხვირიდან კუდამდე ვეტერინარული შემოწმება, წონის შემოწმება და ვაქცინაციის მიმოხილვა. მოიცავს ნაბეჭდი ჯანმრთელობის პასპორტის შინაარსს.",
        "size": "30 min",
        "price": 60.00,
        "tags": ["service", "vet", "wellness"],
    },
    {
        "slug": "service-vet-home-visit",
        "name": "At-Home Vet Visit",
        "name_ka": "სახლში ვეტერინარის ვიზიტი",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_vet"],
        "description": "Vet comes to you — ideal for anxious pets, post-op recovery and senior animals. Tbilisi central districts.",
        "description_ka": "ვეტერინარი მოვა თქვენთან — იდეალურია მღელვარე ცხოველებისთვის, ოპერაციის შემდგომი აღდგენისთვის და ხანდაზმული ცხოველებისთვის. თბილისის ცენტრალური უბნები.",
        "size": "60 min",
        "price": 110.00,
        "tags": ["service", "vet", "home-visit"],
    },
    {
        "slug": "service-pet-taxi",
        "name": "Pet Taxi — Door-to-Vet Transport",
        "name_ka": "ცხოველის ტაქსი — კარიდან ვეტერინარამდე ტრანსპორტი",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_walking"],
        "description": "Climate-controlled van with secure crates. We pick up, transport and (if needed) wait while you visit the vet, then bring you back.",
        "description_ka": "კლიმატ-კონტროლირებული მიკროავტობუსი უსაფრთხო კონტეინერებით. ჩვენ ვიღებთ, გადავიყვანთ და (საჭიროების შემთხვევაში) დაგელოდებით ვიზიტის დროს, შემდეგ უკან მოგიყვანთ.",
        "size": "Per trip",
        "price": 35.00,
        "tags": ["service", "transport", "taxi"],
    },
    {
        "slug": "service-boarding-overnight",
        "name": "Overnight Boarding — Small Group",
        "name_ka": "ღამისთევა — პატარა ჯგუფი",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_boarding"],
        "description": "Home-style overnight stay with no more than 4 pets per host. Two walks a day, supper and breakfast, photo update each evening.",
        "description_ka": "სახლის სტილის ღამისთევა — მასპინძელთან არაუმეტეს 4 ცხოველი. დღეში ორი სასეირნო, ვახშამი და საუზმე, ფოტო შეტყობინება ყოველ საღამოს.",
        "size": "Per night",
        "price": 65.00,
        "tags": ["service", "boarding", "overnight"],
    },
    {
        "slug": "service-pet-sitter-day",
        "name": "In-Home Day Sitter — 4 hours",
        "name_ka": "სახლში მზრუნველი — 4 საათი",
        "brand": "SmartPaw Care",
        "pet_type": "both",
        "image": IMG["service_boarding"],
        "description": "A sitter stays at your place for 4 hours — feeding, walks, play and any meds. Two photo updates included.",
        "description_ka": "მზრუნველი თქვენთან რჩება 4 საათით — კვება, სასეირნო, თამაში და მედიკამენტები. ორი ფოტო შეტყობინება შედის.",
        "size": "4 h",
        "price": 75.00,
        "tags": ["service", "sitter", "in-home"],
    },
]


# ====================================================================================
# Assemble + upsert
# ====================================================================================
def _attach_meta(items: List[Dict], category: str, sub_category: str) -> List[Dict]:
    out = []
    for it in items:
        doc = {
            **it,
            "category": category,
            "sub_category": sub_category,
            "currency": "GEL",
            "status": "published",
            "featured": it.get("featured", False),
        }
        out.append(doc)
    return out


ALL_PRODUCTS = (
    _attach_meta(FOOD, "catalogue", "food")
    + _attach_meta(HYGIENE, "catalogue", "hygiene")
    + _attach_meta(VITAMINS, "catalogue", "vitamins")
    + _attach_meta(TOYS, "specials", "toys-accessories")
    + _attach_meta(TECH, "specials", "innovation-tech")
    + _attach_meta(SERVICES, "specials", "services")
)


async def upsert_all(db, reset: bool = False) -> int:
    """Idempotent: upserts by slug. If reset=True, wipes products first."""
    if reset:
        await db.products.delete_many({})

    now_iso = datetime.now(timezone.utc).isoformat()
    written = 0
    for p in ALL_PRODUCTS:
        slug = p["slug"]
        existing = await db.products.find_one({"slug": slug})
        if existing:
            update = {**p, "updated_at": now_iso}
            await db.products.update_one({"slug": slug}, {"$set": update})
        else:
            doc = {
                "id": str(uuid.uuid4()),
                **p,
                "created_at": now_iso,
                "updated_at": now_iso,
            }
            await db.products.insert_one(doc)
        written += 1

    await db.products.create_index("slug", unique=True)
    await db.products.create_index([("category", 1), ("sub_category", 1)])
    return written


async def main(reset: bool):
    here = os.path.dirname(__file__)
    load_dotenv(os.path.join(here, ".env"))
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    n = await upsert_all(db, reset=reset)
    print(f"Upserted {n} products across 6 sub-categories.")
    client.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", action="store_true", help="Wipe products collection first")
    args = parser.parse_args()
    asyncio.run(main(reset=args.reset))
